feeds:
  - "https://pineman.github.io/atom.xml"
  - "https://boringsql.com/atom.xml"
  - "https://www.cybertec-postgresql.com/en/feed/"
  - "https://postgres.ai/blog/rss.xml"
  - "https://fly.io/blog/feed.xml"
  - "https://vondra.me/index.xml"
  - "https://turbopuffer.com/blog/rss.xml"
  - "https://antirez.com/rss"
  - "https://andrealeopardi.com/feed.xml"
  - "https://andyatkinson.com/feed.xml"
  - "https://andycroll.com/index.xml"
  - "https://antonz.org/all/index.xml"
  - "https://ardentperf.com/feed/"
  - "https://benhoyt.com/writings/rss.xml"
  - "https://avi.im/blag/index.xml"
  - "https://www.pgmustard.com/blog?format=rss"
  - "https://planetscale.com/blog/feed.atom"
  - "https://brandur.org/atoms.atom"
  - "https://brandur.org/fragments.atom"
  - "https://byroot.github.io/feed.xml"
  - "https://politepol.com/fd/gyXZHF9wUG2H.xml"
  - "https://www.craigkerstiens.com/index.xml"
  - "https://www.crunchydata.com/blog/rss.xml"
  - "https://danluu.com/atom.xml"
  - "https://mcfunley.com/feed.xml"
  - "https://dansvetlov.me/feed.xml"
  - "https://danielchasehooper.com/feed.xml"
  - "https://dashbit.co/feed"
  - "https://dave.cheney.net/feed"
  - "https://crawshaw.io/atom.xml"
  - "https://davidgomes.com/rss/"
  - "https://blog.devtrovert.com/feed"
  - "https://eieio.games/feed.xml"
  - "https://elixir-lang.org/atom.xml"
  - "https://kill-the-newsletter.com/feeds/wabk4wdo9qdm89580t7z.xml"
  - "https://explaining.software/rss.xml"
  - "https://arslan.io/rss/"
  - "https://words.filippo.io/rss/"
  - "https://fractaledmind.github.io/feed.xml"
  - "https://golangweekly.com/rss/"
  - "https://goncalo.mendescabrita.com/feed.xml"
  - "https://goncalo.mendescabrita.com/feed/notes.xml"
  - "https://goncalo.mendescabrita.com/feed/tils.xml"
  - "https://grantslatton.com/rss.xml"
  - "https://hakibenita.com/feeds/all.atom.xml"
  - "https://honeyryderchuck.gitlab.io/feed.xml"
  - "https://ivoanjo.me/feed.xml"
  - "https://jazco.dev/atom.xml"
  - "https://jepsen.io/blog.rss"
  - "https://joel.drapper.me/rss.xml"
  - "https://jpcamara.com/feed.xml"
  - "https://judoscale.com/rss.xml"
  - "https://jvns.ca/atom.xml"
  - "https://jvns.ca/til/atom.xml"
  - "https://karpathy.bearblog.dev/feed/"
  - "https://lewiscampbell.tech/blog/feed.xml"
  - "https://feeds.macrumors.com/MacRumors-All"
  - "https://macwright.com/rss.xml"
  - "https://marcoroth.dev/feed.xml"
  - "https://matklad.github.io/feed.xml"
  - "https://blog.mattstuchlik.com/feed.xml"
  - "https://www.mikeperham.com/index.xml"
  - "https://mitchellh.com/feed.xml"
  - "https://multigres.com/blog/rss.xml"
  - "https://www.nateberkopec.com/feed.xml"
  - "https://kill-the-newsletter.com/feeds/ncgh3nvg2upf0qel771h.xml"
  - "https://notes.eatonphil.com/rss.xml"
  - "https://buttondown.com/jaffray/rss"
  - "https://nullpt.rs/feed.rss"
  - "https://getoban.pro/articles/feed"
  - "https://oldmoe.blog/feed/"
  - "https://www.orioledb.com/blog/atom.xml"
  - "http://feeds2.feedburner.com/patshaughnessy"
  - "https://ordep.dev/feed.xml"
  - "https://buttondown.com/peterullrich/rss"
  - "https://pganalyze.com/feed.xml"
  - "https://pgdog.dev/feed.xml"
  - "https://www.phoenixframework.org/feed"
  - "https://politepol.com/fd/TICeWLZT7ssb.xml"
  - "https://jdx.dev/posts/index.xml"
  - "https://blog.nelhage.com/atom.xml"
  - "https://solnic.dev/posts/index.xml"
  - "https://programmingisterrible.com/rss"
  - "https://www.putsdebug.com/feed.xml"
  - "https://railsatscale.com/feed.xml"
  - "https://rakyll.org/index.xml"
  - "https://rescrv.net/feeds/all.atom.xml"
  - "http://research.swtch.com/feed.atom"
  - "https://blog.deobfuscate.io/atom.xml"
  - "https://world.hey.com/ricardo.tavares/feed.atom"
  - "https://rcrowley.org/index.atom.xml"
  - "https://riverqueue.com/blog.atom"
  - "https://www.ruby-lang.org/en/feeds/news.rss"
  - "https://rubyonrails.org/feed.xml"
  - "https://us11.campaign-archive.com/feed?u=1aa0f43522f6d9ef96d1c5d6f&id=840412962b"
  - "https://rubyweekly.com/rss/"
  - "http://samsaffron.com/posts.rss"
  - "https://samwho.dev/rss.xml"
  - "https://www.scattered-thoughts.net/atom.xml"
  - "https://seiya.me/atom.xml"
  - "https://www.depesz.com/feed/"
  - "https://ankane.org/feed.rss"
  - "https://sirupsen.com/atom.xml"
  - "https://brutecat.com/rss.xml"
  - "https://solnic.dev/rss/"
  - "https://sorentwo.com/feed.xml"
  - "https://www.sougou.io/feed/"
  - "http://tenderlovemaking.com/atom.xml"
  - "https://www.theerlangelist.com/rss"
  - "https://go.dev/blog/feed.atom"
  - "https://bcantrill.dtrace.org/index.xml"
  - "https://thmsmlr.com/rss"
  - "https://this-week-in-rust.org/rss.xml"
  - "https://thorstenball.com/atom.xml"
  - "https://transactional.blog/feed.xml"
  - "https://thume.ca/atom.xml"
  - "https://unplannedobsolescence.com/atom.xml"
  - "https://www.zachdaniel.dev/feed"
  - "https://zackoverflow.dev/rss.xml"
